#!/usr/bin/env node
/*jshint node: true */

'use strict';

var npm = require('npm');

npm.load(function (err) {
    if (err) {
        throw err;
    }

    npm.commands['run-script'](['test'], function (err) {
        if (err) {
            console.error('Precommit hook failed!');
            console.error(err);
            process.exit(1);
        } else {
            console.info('Precommit hook ran successfully.');
        }
    });
});
